config/routes.rb
RottenMangoes2::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'

  namespace :admin do
    resources :users
  end
end

  

app/models/movie.rb
class Movie < ActiveRecord::Base
  
  mount_uploader :image, ImageUploader

  has_many :reviews

  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validates :description,
    presence: true

  validates :poster_image_url,
    presence: true

  validates :release_date,
    presence: true

  validate :release_date_is_in_the_future

   def review_average
    if reviews.any?
      reviews.sum(:rating_out_of_ten)/reviews.size
    end
  end

  def self.search(search)
    if search
      # if !search title.empty?&& !searchc director.empty?
      #   Movie.where("title LIKE ? OR director LIKE ?","%#{search[:title]}%","%#{search[:director]}%" )
      # elsif title
      #   Movie.where("title LIKE ?", "%#{search[:title]}%")
      # else # dirctore present
      #   Movie.where("director LIKE ?", "%#{search[:director]}%")
      # end

      if search[:title] && search[:director].empty?
        movies = Movie.where("title LIKE ?", "%#{search[:title]}%")
      elsif search[:title].empty? && search[:director]
        movies = Movie.where("director LIKE ?", "%#{search[:director]}%")
      else
        movies = Movie.where("title LIKE ? OR director LIKE ?","%#{search[:title]}%","%#{search[:director]}%" )
      end      
      # if search[:duration] != "0"
      #   result=[]
      #   binding.pry
      #   movies.each do |movie|
      #     if search[:duration] == "1" && movie.runtime_in_minutes < 90
      #       result << movie
      #     elsif search[:duration] == "3" && movie.runtime_in_minutes > 120
      #       result << movie
      #     elsif movie.runtime_in_minutes >= 90 && movie.runtime_in_minutes <= 120
      #       result << movie
      #     end
      #   end
      #   result.first
      # end
    else
      all
    end
  end

  protected
 
  def release_date_is_in_the_future
    if release_date.present?
      errors.add(:release_date, "should probably be in the future") if release_date < Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews

  def full_name
    "#{firstname} #{lastname}"
  end 

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :must_be_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # session[:user_id] = @user.id
      redirect_to admin_users_path, notice: "You created and logged in as #{@user.firstname}!"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    # @user.destroy
    # binding.pry
    # respond_to do |format|
    #   if 
    @user.destroy
    binding.pry
    if @user.destroyed? 
        # binding.pry
        # Tell the UserMailer to send a welcome email after save
    UserMailer.byebye_email(@user)
    else

    #some other stuff.  
 
        # format.html { redirect_to admin_users_path }
        # format.json { render json: @user, status: :created, location: @user }
      # else
      #   format.html { render action: 'new' }
      #   format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
    # @user = User.find(session[:user_id])
    
    end
    redirect_to admin_users_path
  end

  protected

  def must_be_admin
    if !current_user || !current_user.admin
      flash[:error] = "must be a admin"
      redirect_to new_session_path
    end
  end

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end
##########################################################################################

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      # Prevent CSRF attacks by raising an exception.
      # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  # before_action :must_be_logged_in
  def index
    @movies = Movie.search(params[:search])
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    if current_user
      @movie = Movie.new
    else
      redirect_to new_session_path, notice: "Please sign in first"
    end
  end

  def edit
    if current_user
      @movie = Movie.find(params[:id])
    else
      redirect_to new_session_path, notice: "Please sign in first"
    end
  end

  def create
    @movie = Movie.new(movie_params)
    binding.pry
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    if current_user
      @movie = Movie.find(params[:id])

      if @movie.update_attributes(movie_params)
        redirect_to movie_path(@movie)
      else
        render :edit
      end
    else
      redirect_to new_session_path, notice: "Please sign in first"
    end
  end

  def destroy
    if current_user
      @movie = Movie.find(params[:id])
      @movie.destroy
      redirect_to movies_path
    else
      redirect_to new_session_path, notice: "Please sign in first"
    end
  end

  protected
  
  # def must_be_logged_in
  #   unless current_user
  #     redirect_to movies_path
  #   end
  # end

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :image
    )
  end

end 

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_movie
  before_filter :restrict_access
  
  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for @user, url: admin_user_path(@user) do |f| %>
  <div>
    <%= f.label "firstname" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "email" %><br>
    <%= f.email_field "email" %>
  </div>
  <div>
    <%= f.label "admin" %><br>
    <%= f.check_box "admin" %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end%>

app/views/admin/users/edit.html.erb
<%= link_to "Back to this user", admin_user_path(@user) %>

<h2>Edit this user.</h2>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Create a new user!", new_user_path %>
<hr>
<% @users.each do |user| %>
  <h2><%= link_to user.full_name, admin_user_path(user) %></h2>
  <h2><%= user.email %></h2>
  <h3><%= formatted_date(user.created_at) %> <h3>
  <h3><%= formatted_date(user.updated_at) %> <h3>
  <h3>admin: <%= user.admin%></h3>
  <hr>
<% end %>

app/views/admin/users/show.html.erb
<%= link_to "Back to all users", admin_user_path %><br/>

<h2><%= @user.full_name %> (<%= link_to "edit", edit_admin_user_path(@user) %>, <%= link_to "delete", admin_user_path(@user), method: :delete, confirm: "Delete user #{@user.full_name}?" %>)</h2>
<h2>Email: <%= @user.email %></h2>
<h3>Created at: <%= formatted_date(@user.created_at) %></h3>
<h3>Updated at: <%= formatted_date(@user.updated_at) %></h3>
<h3>Admin: <%= @user.admin %></h3>
<hr>

app/views/layouts/_footer.html.erb
 <footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
      <% if current_user.admin %>
        <%= link_to "See users", admin_users_path %>
        Signed in as ADMIN
      <%end%>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date" %>
  </div>
  <div>
    <%= f.label "director" %><br>
    <%= f.text_field "director" %>
  </div>
  <div>
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.number_field "runtime_in_minutes" %>
  </div>
  <div>
    <%= f.label "poster_image_url" %><br>
    <%= f.text_field "poster_image_url" %>
  </div>
  <div>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_area "description" %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<%= link_to image_tag(movie.poster_image_url), movie_path(movie) %>
<%= link_to image_tag(movie.image), movie_path(movie) %>
<h2><%= link_to movie.title, movie_path(movie) %></h2>
<h2><%= movie.review_average %>/10</h2>
<h3><%= formatted_date(movie.release_date) %> <h3>
<h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
<p><%= movie.description %></p>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Submit a movie!", new_movie_path %>
<hr>
<div class="searchbar">
  <%= form_tag movies_path, method: "get" do %>
    <%= label_tag(:movies,"Search for:") %>
    <%= text_field_tag("search[title]" )%>
    <%= text_field_tag("search[director]") %>
    <%= select_tag("search[duration]", options_for_select(
      [
        ["Select an option", 0],
        ["Under 90 minutes", 1],
        ["Between 90 and 120 minutes",2],
        ["Over 120 mintues",3]
      ]
    ) ) %>
    <%= submit_tag("Search", name: nil) %>
  <%end%>
</div>



<hr>
<% @movies.each do |movie| %>
  <%= render partial: "movie", object: movie %>
<% end %>
<hr>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= link_to image_tag(@movie.poster_image_url), movie_path(@movie) %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
<h2><%= @movie.review_average %>/10</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label "rating_out_of_ten" %><br>
    <%= f.number_field "rating_out_of_ten" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.email_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div>
    <%= f.label "admin" %><br>
    <%= f.check_box "admin" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>